### ISSUE TITLE
Detailed description is not commited

### ISSUE THREAD

**Issue by grandeljay** [Everduin94/better-commits#47]
I've noticed this a couple times while writing a detailed description of the commit. It simply won't show when I look at the commit on GitHub or similar.

Can you reproduce this behaviour?

**Comment by Everduin94** [comment]
What screen on Github does it not show on? Is the description in your `git log`?

I have seen if you commit multiple times before your first push, it won't auto populate the PR description or merge commit? I can't exactly remember, and I see that more often at my work than in my side projects. -- But not sure if we're talking about the same screen/situation

**Comment by grandeljay** [comment]
> Is the description in your git log?

No, also not.

> I have seen if you commit multiple times before your first push, it won't auto populate the PR description or merge commit?

Yes, I have also noticed that.

> But not sure if we're talking about the same screen/situation

Yeah, I am talking about a regular commit without any branches or merges. It used to work I think but after the most recent update I feel like it stopped :/

Does it work for you?

**Comment by grandeljay** [comment]
I ran another test. Am I doing something wrong? Is it my terminal?

![image](https://github.com/Everduin94/better-commits/assets/45571053/fd7b8048-31da-4585-87b4-740cb3547a35)

**Comment by Everduin94** [comment]
@grandeljay I'm traveling rn so I have to test on my laptop but reply on my phone 😅

I have the latest 1.5.1, and the description shows in my git log

We haven't really changed any functionality around description. There have been changes to ticket inference and ticket position in the title, but not much else in the latest releases

https://github.com/Everduin94/better-commits/blob/main/src/index.ts#L260-L265

If I had to guess, I think its because you're using command prompt or windows?

It might be the new line delimiter doesn't work on command line or windows. I would download something like Hyper Terminal and try that. -- but I think you mentioned it used to work for you, was that also with command prompt?

For context, whatever is in that preview gets passed straight to git commit -m. 

I use arch linux and MacOS. I do have a windows partition I could test on, but I'm away from home for the next week.

**Comment by grandeljay** [comment]
Sorry, I just noticed I was still using `v1.1.1`. I just upgraded to `v1.5.1`. That will probably fix my issue. I will reopen if it doesn't, for whatever reason if that's okay with you.

Thank you for your time! And enjoy your time away (hopefully on vacation!)
