### ISSUE TITLE
Want to add Alias for better-commits cmd. 

### ISSUE THREAD

**Issue by awaisalwaisy** [Everduin94/better-commits#63]
I want to add Alias for better-commits cmd. Any recommended way?

**Comment by Everduin94** [comment]
Depends on the tools you use or how you might want to use it.

You can create a bash/zsh alias for it in your `.zshrc` or `.bashrc` 

```sh
alias bc='better-commits'
alias bb='better-branch'
```

Or if you want to implement it in a node/js project you could place a script in your `package.json`

```json
"scripts": {
  "bc": "npm run better-commits",
}
```

I wouldn't recommend trying to overwrite something like `git commit`. Because things like `git commit -m` can be much faster when you don't need a conventional commit like "address pr comments" etc.

Also the repository has a Github discussions where you can ask questions like the one in this issue :)  https://github.com/Everduin94/better-commits/discussions

Hope that helps!
